apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pipis-cluster
  namespace: pipis-db
spec:
  instances: 3
  storage:
    size: 1Gi
  # bootstrap:
  #   initdb:
  #     database: pipis-db
  #     owner: appuser
  #     secret:
  #       name: appuser-secret