apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: api-gateway
          image: 410445721302.dkr.ecr.mx-central-1.amazonaws.com/pipis-staging/api-gateway
          ports:
            - containerPort: 3000