apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: frontend
          image: 410445721302.dkr.ecr.mx-central-1.amazonaws.com/pipis-staging/frontend

          envFrom:
            - configMapRef:
              name: frontend-configmap
          ports:
            - containerPort: 3030