apiVersion: v1
data:
    password: ENC[AES256_GCM,data:enSNXgmWARfmyLE1mucyf2tgjDvqG7YfzItyBQ==,iv:18ga1NIyE6fP9rLcp6GolYR0OcgvaAzSdrAg7M88Rk8=,tag:IX80yrUB7EdeZj2TX/iGOg==,type:str]
    username: ENC[AES256_GCM,data:TWL9SP92B7k=,iv:gnyYxpF5F0N+CTtm608sjed4GV6rSHL32/s4b1A/O5A=,tag:r/x3GYkzsrfdWXQMHoO4Rg==,type:str]
kind: Secret
metadata:
    name: appuser-credentials
sops:
    age:
        - recipient: age1cfj3gtr4rjm8hst3asx5q8dtpnp406szynxx4mpxwuak03c4aacszqw8ay
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT1RwZmlnckR4d1FFWE9T
            am0rZmtYYVVxRVdpUmhEMHAvQ2Nrc0lrbmdjCkExS1RaSmZaSUh2K0l0SUxyeUFw
            Ykp0aGN5RDFxUlEweVZFMFpwdlpjU1kKLS0tIGRyMVpBYnc0L0hBWEZmUjdWQXhp
            bGJkTzVUcmZrcXRYbWVaSnVHUVAyYlEKmQaTA3lOCRWLddLvoZzPg0hhLXd6rkGV
            BtQ2UexJ+B9K5XsavDuX3yxLRmF1VafQqBupBjIcCDUafyViTta9Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T00:19:24Z"
    mac: ENC[AES256_GCM,data:fAy4QHmBkbgigFE5sq9YS3qjHwVHV1XSJ3LBWOdhHcyIFUsZvnaPJ8dUpakUij+qoA+XVVbP7SEkZYhrXwciGee+AbhMulf8GilP+m+NkUQBooSz4ae96uxW+GbppY4n+MxxsHdvoBrxFKUcsGrZqzL4RQ/KSw4QUntHnIdmkmU=,iv:m7qdWTKK9R3pLVFQDqpbxXAklcSpVni416/J7Mhe1AU=,tag:K4QOTPLIqrcePOusBH19Yw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
