apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: pipis
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:eR22+lFmuXqo/CxyLGSb7nmRBQA=,iv:a5J2u0qzzdyOR1M1k7H1SWrETDpaUWutTA2XP+PPS1Y=,tag:YLt0w433kUEJpZJ09XeU1w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7rLLyQ/vqfk+y6xnLWR15y1G84vfzbTqPIvDhBKGQOcfHrHC5XsjXQ==,iv:viNUhIvj3vf0MZXxyinpO8QK/W7dTKz1TVii/zM72X0=,tag:IaEuhCwiA2n/yJp8wzCXBg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:yeQpFCrkWMrKDYyx,iv:azmtWTDGj8vcfDcpVxYEIop69kIQTjZb0lSuJjFGGRw=,tag:lzNSH+IenOwhSPiFN2B9Eg==,type:str]
    AWS_ACCOUNT_ID: ENC[AES256_GCM,data:JsL4zkilXTI5Alrx,iv:8dmQ6U5ZJBtz9YDIRvd/M3yEt/Ph8B6tut45sXBoZCA=,tag:TsStTQ5inywMIFplYgDxgw==,type:str]
sops:
    age:
        - recipient: age1cfj3gtr4rjm8hst3asx5q8dtpnp406szynxx4mpxwuak03c4aacszqw8ay
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOEw1N3B5dFFydmFTMTdh
            TkJNaC93b0EzbUIxMHFTTHRZWjJqaGRkSm1FCjBlTDUzRFVibjY3RWZjSUh2L1Uy
            VjJHZ1NxM3dTaTdRQkFjU1JuaVMvYmsKLS0tIG10ODJUZW4xTFlDUHJ3djZ5MnhC
            V0dwbFJKSG1tYk5IRVpIY1lBTkZVNTAKYSjjKqX9jXFQGSckxdIATUlBv+6bBkIF
            SrOcCPPQKVOR17HNsDAUgZT6VYIU6RO/vor6gWmGVU/0jppGtIDi5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T19:55:08Z"
    mac: ENC[AES256_GCM,data:DP51B9nWAygRVmneAvSVhaq3E/KLR5GU9fLQ4EdrYZeVdHhz2t4Hx1oVXE4OF6gRz2FFf3s3HBI6BL3jwiXTqTdmosbO/5wjjvXMActudFY1XVj0JecLg+bafFMkkD3+GeAF1AztzSYybHx0w1JHxULx7q/oSmljuVoZfABOVCM=,iv:+I2iR5jGy/xvfLSoNU9stp5PHoYQKLORz4ZK6H7Fp68=,tag:d59w7KzaXNV9ehDBWzL0sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
