apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: pipis
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:xSr8n95y56V11i3tA9eNiZynD4U=,iv:1XZlRUgCGGFfmOuXuNP9ihRbruMSg2Xt4tKGPzHFolo=,tag:NvFXg7zgA8Mg81M463KNHA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PavZ9LxAdh7WFdp4KBT9RjlDBxwNbbe/fRuqKxV71ArcXjeWkSJDYQ==,iv:aXo9D5kav4ttNjYGvOSZQBbcgHAkJZfZPBI+q2kT8WE=,tag:eD4n9on2SlVRrKrwi9diWg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:jhEsO+aVw0MOQreH,iv:jOregC/bG4A8zHxhXsp4vKXSaBScXf5GbYG5o84p6Zg=,tag:1l3PRqTKNUA4KvBiZjpm+A==,type:str]
    AWS_ACCOUNT_ID: ENC[AES256_GCM,data:x9g3rU2BOHTafUfi,iv:3YZGXa44ftOACvyaK2tgsy3jINftXj42kkrEzSvZTUk=,tag:/7q1pA+8EmcSe7Eb02YzpQ==,type:str]
sops:
    age:
        - recipient: age1cfj3gtr4rjm8hst3asx5q8dtpnp406szynxx4mpxwuak03c4aacszqw8ay
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZ0hMWVFPSUdvUE9mcWtP
            VWhiQ25wblFyajhUdlVTWGFPT05EaXJ3bFE0CmxzRGljbEJYcVRKeGZTQXZXNkRG
            TjZDVFZnN0hSbjY3elhGcmZ3ZytDUFkKLS0tIExuRDFYTEc3MnBwT0xpS0ZKVTJV
            dnlpV2lXZER3bU1qaUhyWlZxV0trd2MKvzodGXpqXh6kFd/gpTegTeMxLJ+3vRtN
            r4LjlbILRhvR45hwPDZlXcR5CrYGDufyF80ajpfwLd+0h0HT2/ZJuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T23:58:03Z"
    mac: ENC[AES256_GCM,data:0XRMUijfc2WEQBunOoiKhyT9UiO7RfrTbAtj1ezA4AWlytM88rBywtjkaAGmarG515xuh1aj77juq7opoxENVhTb+z4tllTU0z1KkfdOuRynkC5FtU6/esYxP7ISo/XzyKy5//iraH6sD8r11tWuP5WDc+7e1oWg9tl89A1RRLo=,iv:l7MY3Ha8KNlcu/m7Sl6wpudB3rDRuU+H2135/dHQaOE=,tag:R0nZIL3e0pxgiXl+ibdBlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
