apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: pipis
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:M2yF6mOVPvCC54f84vklZ41t3JE=,iv:TWyV8k3HHj2Ao/tWUZlDTA0H8MzMlquNsSaAUY7FxaU=,tag:gycPHUlwSSChDTvg3fbpRA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VYthkNJ7qs5qru9AxWneQ2Hr9y55MzumX3OKB4utHhgxIAEK/KRjLQ==,iv:pvXqHXTJYqKBruHB4tJ9XnWsqm8us2AqfXvSowd75Ng=,tag:6synzb1Vt8SiHT6A4i/GCg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:s2IkzlsTVorVEdWR,iv:kFaq54ELWAWCzqtzdQQv2xSudnBy6Nns4zavegjsB3Y=,tag:xvm81n+m1EC9gElhqPo0jQ==,type:str]
    AWS_ACCOUNT_ID: ENC[AES256_GCM,data:qCGGHPj/zEB3I1qb,iv:Rnhk2Tm0t7ZBQowU64QODetqxd2FwnEeua2Jg4lH3zo=,tag:Z0PsrP68+uCJQYwX8uz4WA==,type:int]
sops:
    age:
        - recipient: age1cfj3gtr4rjm8hst3asx5q8dtpnp406szynxx4mpxwuak03c4aacszqw8ay
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQWVkSWF0Qm5Zejl2c2dX
            UjFhWTJGem5GTFpPUmhvb3hRMWFTWkY0cldFCmpmYlYzS3BhUDlxMWJ5K2FBMnpj
            aCs5a1E4WWE5VjBUb3gxN2dkZ2hDd00KLS0tIHRNVlh4TmIyd1FlM0FUek9uMmJO
            VWNtNGsybFNGLzRnYkZKN0JzNUhPME0Kbu705Wdq3BHHYW3FD8WyOXC8TLuiAjKv
            u5Gk7MmisV2o33vQIdqpHVB83SZYOsih/CjZZRKAWmI1aqQr2cuJAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T18:59:31Z"
    mac: ENC[AES256_GCM,data:6zMNpqGvNRM+avh0TJLvaGV/HgsnnTJeAgk/hfgyXhCDTyExOiDlWfWgX4pTfE1dQSQZRG4lZ4OK6BHJ4Ux61cnD47I2zee4kpl/fQWocFrA/aeHYJCxe7zXtFvKnf1Gx/6/OfMiporEMB6TKLrlyMPg0wbPhvMB7Td05p12LPg=,iv:LeXt8/dhE7YAwqkDbzOwvqBQGJIzfbl8U5Yq4aAUS5Y=,tag:Tb+DGF0iStfuEfD8Hs/myg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
