apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pipis
resources:
  - ../../base/pipis
  - tunnel-token.yaml
  - cloudflare.yaml
  - aws-credentials.yaml
  - ecr-token-refresh-sa.yaml
  - ecr-token-refresh-rbac.yaml
  - ecr-token-refresh-cronjob.yaml