apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
stringData:
    token: ENC[AES256_GCM,data:NvM1fzOHNy70j7r6fKhKBkpfAGjpIzrme1PGeUxDQZht9bI7INKFeHLFGUM1LMPuUYTk3iUMt1zktPw6sYOUKr27z0LiJ5aAnxXZYYxdrWyze0nf+w8pJwZxeXmmRppZBoTZidGy7R/rCjZHwTiIbfFRVPnDNOxuBV2HpX4vpz3oLI77z3QmStTg/QJJWUbzusrvnrBRueAnTX4yYg3HLDh5DZzNSWs5/PAyd2wopVYz9M++kF43AA==,iv:b7GQiOHSR0KsJuhrVowemcv6uM5Dcx83pkTLA/Irnb0=,tag:zxY2FF6rkUKveOFSifaKhw==,type:str]
sops:
    age:
        - recipient: age1cfj3gtr4rjm8hst3asx5q8dtpnp406szynxx4mpxwuak03c4aacszqw8ay
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVXg1amtXODBwNVF3T3NK
            YmI3bjNUQVJzZGpLMysvaktqVnhDMFVsdFdJClNoRWNNM04rd1B5Ni9TaktudmRR
            M2tCVlRnSzFFeUFYa0tXR0p5enlFSEEKLS0tIFFIbS9xM3NZczI2MnQ0bVVJZ1hL
            YXJWS1VRR0RPTmZQTHA0YzVpWHQwUEkKeKWpENFF56lxI6dha7FLa6DimT/zPs8x
            jw0/Y/FekdHYu1XhZBebogrBxRPxjHYn4EKHpAuwJ2ITzQ2AKswAuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T19:56:23Z"
    mac: ENC[AES256_GCM,data:YO6B94RKhGgoG3Nl8WBkqS+AvY2WUskZTU6xUKRdrItWYZaSbSq98Tq0In8dvmeuvgWsuwrF4AyG7xzt3RM9jICeu2B97AS3avcJUHPlaYoAjipI3kp4aUEkL0IrVDIwpAgnrvUpSuSgaUfmLM8N/iPn7mYrVJD8a/bH51pN+o4=,iv:5HpCUEBS6Qwd1981ROijbV6zR3O6GV7L0WbDrOvEGoQ=,tag:AmGbfcMk70jgleSH3+qwkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
